print("Please tell me your age:", end=" ")
age = input()
print(f"Currently you are {age} years old.")
print(f"In 10 years, you'll be {int(age) + 10} years old.")
print(f"In 20 years, you'll be {int(age) + 20} years old.")
print(f"In 30 years, you'll be {int(age) + 30} years old.")